### PR TITLE
Inject runtime URLs in the back-end served index.html

### LINKED ISSUE #65: WebSocket subscription fails due to 'insecure operation'
```
Uncaught (in promise) DOMException: The operation is insecure.
    _doConnect event.js:1
    connect event.js:1
    doEventsSubscriptionInit index.js:1
    t4 index.js:1
    t4 index.js:1
    doEventsSubscriptionInit index.js:1
    init index.js:1
    a index.js:1
event.js:1:8459
```

Which prevents the UI from loading, caused by the fact that the ManagerConfig expects an URL that contains HTTP/HTTPs to determine WS/WSS

### PR DESCRIPTION
**Pull request by dominiquekleeven**
Closes #65 

Currently the front-end bundle contains relative URLs that are embedded during its built process. This bundle is then served by the back-end service.

This change allows the back-end to dynamically inject the configured server URL environment variables into the served `index.html` which is then used by the front-end as runtime config. This is more flexible and reliable than relying on embedded relative URLs. It only injects the necessary variables and does not expose anything else.

**The change also resolves an issue where the WS subscription would fail** since the `ManagerConfig` expects the managerUrl to be absolute (e.g. containing the full address), to determine whether it should use WS or WSS.
```
this._endpointUrl = (managerUrl.startsWith("https:") ? "wss" : "ws") + "://" + managerUrl.substr(managerUrl.indexOf("://") + 3) + "/websocket/events";
```

### CODE REVIEW

**Comment by dominiquekleeven** [comment]
Deployed on `test4`

File: frontend/src/index.ts [hunk 1]
```diff
@@ -33,7 +33,7 @@ import './components/breadcrumb-nav';
 import './components/alert-message';
 
 const DEFAULT_MANAGER_CONFIG: ManagerConfig = {
-    managerUrl: ML_OR_URL || '/',
```
Comment (MartinaeyNL) [inline frontend/src/index.ts:36]: I assume you removed this fallback to allow `ML_OR_URL` to be an empty value.
I think if you replace `||` with `??`, it should still work, because it's a better null check.

```
managerUrl: MR_OR_URL ?? '/'
```

File: src/service_ml_forecast/api/web_route.py [hunk 2]
```diff
@@ -40,6 +41,24 @@
...
+
+    runtime_config = {
+        "ML_SERVICE_URL": ENV.ML_API_ROOT_PATH,
+        "ML_OR_URL": ENV.ML_OR_URL,
+        "ML_OR_KEYCLOAK_URL": ENV.ML_OR_KEYCLOAK_URL,
+    }
+    config = json.dumps(runtime_config).replace("<", "\\u003c")
+    html = index_path.read_text(encoding="utf-8")
+    html = html.replace("__ML_RUNTIME_CONFIG__", config)
+    return HTMLResponse(content=html)
```
Comment (MartinaeyNL) [inline src/service_ml_forecast/api/web_route.py:59]: I would use a more popular pattern to inject variables like this,
using a global configuration object, like `window`.

```
<script>
  // Using a namespace like 'APP_CONFIG' to avoid polluting the global scope
  window.OR_ML_SERVICE_URL = {{ value }};
</script>
```

**Review by MartinaeyNL — COMMENTED** [review]
Yeah this PR is fine with me.
I've only got two minor comments to simplify the scope to `window`, instead of global variables.
I'm not sure whether we should also follow a similar practice for the OpenRemote repository,
but this pattern is perfectly fine within a specific project like this.

File: frontend/src/index.ts (hunk 1 above)
Comment (dominiquekleeven) [reply frontend/src/index.ts:36]: Uses nullish coalesce now, thanks! I keep forgetting it exists haha.

File: src/service_ml_forecast/api/web_route.py (hunk 2 above)
Comment (dominiquekleeven) [reply src/service_ml_forecast/api/web_route.py:59]: Changed it to make use of window, thanks!

**Review by MartinaeyNL — APPROVED** [review]
